site_name: The Cabinet of Curiosities
site_description: A Collection of Jesal's eclectic interests
site_author: Jesal Mehta
copyright: Copyright 2024 Jesal Mehta - Creative Commons Attribution Non Commercial

nav:
  - Home: index.md
  - About Me: about.md
  - Thingamajigs :
    - MiniLoom : mini_loom.md
    - Makings : makings.md
    - Creative Coding : creative_code.md
    - Notes on this site : site_notes.md
  
extra:
  # Set your own social media below (or remove)
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/cabofcuriosity
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jesal-mehta-8762404a/

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: custom
    accent: indigo
  font:
    # See available fonts at https://fonts.google.com/
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: material/tortoise
  favicon: images/favicon.svg
  features:
    # - navigation.tabs
    # - navigation.instant

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - markdown_captions
  - attr_list

plugins:
  - mkdocs-video

extra_css:
  - stylesheets/extra.css