site_name: The Cabinet of Curiosities
nav:
  - Home: index.md
  - About Me: about.md
  - Thingamajigs :
    - MiniLoom : mini_loom.md
    - Makings : makings.md
    - Creative Coding : creative_code.md
    - Notes on this site : site_notes.md
  

theme:
    name: material

markdown_extensions:
  - attr_list

plugins:
  - mkdocs-video
