site_name: The Cabinet of Curiosities
site_description: A Collection of Jesal's eclectic interests
site_author: Jesal Mehta
copyright: Copyright 2024 Jesal Mehta - Creative Commons Attribution Non Commercial

nav:
  - Home: index.md
  - About Me: about.md
  - Thingamajigs :
    - MiniLoom : mini_loom.md
    - Makings : makings.md
    - 3D Printing :
      - Print Projects :
        - Mecha : 3dp/3DP_mecha.md
        - Flexures : 3dp/3dp_flexures.md
        - PolyHedra : 3dp/3dp_polyhedra.md
      - The year in printing :
        - 3DP in 2019 : 3dp/3DP_2019.md  
        # - 3DP in 2020 : 3dp/3DP_2020.md
        # - 3DP in 2021 : 3dp/3DP_2021.md
        # - 3DP in 2022 : 3dp/3DP_2022.md
        # - 3DP in 2023 : 3dp/3DP_2023.md
        # - 3DP in 2024 : 3dp/3DP_2024.md
        # - 3DP in 2025 : 3dp/3DP_2025.md
  - Wild wild web :  
    - Dot Mandala Generator : dotMandalaTool.md
    - Tracery Bots :  
      - Tracery Bots : traceryBots.md
      # - Trippy Gourmet : trippyGourmet.md
      - Trippy Gourmet : https://jesmehta.github.io/TraceryBots/TrippyGourmetBot/
      - Mad Solutionist : https://jesmehta.github.io/TraceryBots/MadSolutionistBot/
    - Twine : emergent_twine.md
    - Creative Coding : creative_code.md
  - Form follows f(x) :  
    - Form follows f(x) : fffx/formFollowsFx.md
    - Particle systems : fffx/particleSystems.md
    - 100 Gradients : fffx/100Gradients.md
    - Vera Molnar : fffx/VeraMolnarRetrospective.md
  - Notes on this site : site_notes.md

  
extra:
  # Set your own social media below (or remove)
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/cabofcuriosity
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jesal-mehta-8762404a/

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: custom
    accent: indigo
  font:
    # See available fonts at https://fonts.google.com/
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: material/tortoise
  favicon: images/favicon.svg
  features:
    # - navigation.tabs
    # - navigation.instant
    - navigation.expand
    # - navigation.sections

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - markdown_captions
  - attr_list

plugins:
  - mkdocs-video

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/extra.js
